FROM node:10.9

WORKDIR /usr/src/app

RUN npm install -g lerna

# http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/
COPY package.json .

RUN npm install --quiet --unsafe-perm

COPY packages/server ./packages/server
EXPOSE 4000

COPY lerna.json .
RUN lerna bootstrap

CMD [ "yarn", "dev:backend" ]
